/* Automatically generated by p4c-ubpf from ../testdata/p4_16_samples/ipv4-actions_ubpf.p4 on Fri Nov 13 13:07:14 2020
 */
#ifndef _P4_GEN_HEADER_
#define _P4_GEN_HEADER_
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
#include "ubpf_common.h"


enum ubpf_action{
ABORT,
DROP,
PASS,
REDIRECT,
};

struct standard_metadata {
    uint32_t input_port; /* bit<32> */
    uint32_t packet_length; /* bit<32> */
    enum ubpf_action output_action; /* ubpf_action */
    uint32_t output_port; /* bit<32> */
    uint8_t clone; /* bool */
    uint32_t clone_port; /* bit<32> */
};

struct Ethernet_h {
    uint64_t dstAddr; /* EthernetAddress */
    uint64_t srcAddr; /* EthernetAddress */
    uint16_t etherType; /* bit<16> */
    uint8_t ebpf_valid;
};

struct IPv4_h {
    uint8_t version; /* bit<4> */
    uint8_t ihl; /* bit<4> */
    uint8_t diffserv; /* bit<8> */
    uint16_t totalLen; /* bit<16> */
    uint16_t identification; /* bit<16> */
    uint8_t flags; /* bit<3> */
    uint16_t fragOffset; /* bit<13> */
    uint8_t ttl; /* bit<8> */
    uint8_t protocol; /* bit<8> */
    uint16_t hdrChecksum; /* bit<16> */
    uint32_t srcAddr; /* IPv4Address */
    uint32_t dstAddr; /* IPv4Address */
    uint8_t ebpf_valid;
};

struct Headers_t {
    struct Ethernet_h ethernet; /* Ethernet_h */
    struct IPv4_h ipv4; /* IPv4_h */
};

struct metadata {
};


enum ubpf_map_type {
    UBPF_MAP_TYPE_ARRAY = 1,
    UBPF_MAP_TYPE_HASHMAP = 4,
    UBPF_MAP_TYPE_LPM_TRIE = 5,
};
struct ubpf_map_def {
    enum ubpf_map_type type;
    unsigned int key_size;
    unsigned int value_size;
    unsigned int max_entries;
    unsigned int nb_hash_functions;
};

struct pipe_filter_tbl_key {
    uint32_t headers_ipv4_srcAddr; /* headers.ipv4.srcAddr */
};
enum filter_tbl_0_actions {
    pipe_set_ipv4_version,
    pipe_set_ihl,
    pipe_set_diffserv,
    pipe_set_identification,
    pipe_set_flags,
    pipe_set_fragOffset,
    pipe_set_ttl,
    pipe_set_protocol,
    pipe_set_srcAddr,
    pipe_set_dstAddr,
    pipe_set_srcAddr_dstAddr,
    pipe_set_ihl_diffserv,
    pipe_set_fragOffset_flags,
    pipe_set_flags_ttl,
    pipe_set_fragOffset_srcAddr,
    pipe_Reject,
    pipe_filter_tbl_NoAction,
};
struct pipe_filter_tbl_value {
    enum filter_tbl_0_actions action;
    union {
        struct {
            uint8_t version;
        } pipe_set_ipv4_version;
        struct {
            uint8_t ihl;
        } pipe_set_ihl;
        struct {
            uint8_t diffserv;
        } pipe_set_diffserv;
        struct {
            uint16_t identification;
        } pipe_set_identification;
        struct {
            uint8_t flags;
        } pipe_set_flags;
        struct {
            uint16_t fragOffset;
        } pipe_set_fragOffset;
        struct {
            uint8_t ttl;
        } pipe_set_ttl;
        struct {
            uint8_t protocol;
        } pipe_set_protocol;
        struct {
            uint32_t srcAddr;
        } pipe_set_srcAddr;
        struct {
            uint32_t dstAddr;
        } pipe_set_dstAddr;
        struct {
            uint32_t srcAddr;
            uint32_t dstAddr;
        } pipe_set_srcAddr_dstAddr;
        struct {
            uint8_t ihl;
            uint8_t diffserv;
        } pipe_set_ihl_diffserv;
        struct {
            uint16_t fragOffset;
            uint8_t flags;
        } pipe_set_fragOffset_flags;
        struct {
            uint8_t flags;
            uint8_t ttl;
        } pipe_set_flags_ttl;
        struct {
            uint16_t fragOffset;
            uint32_t srcAddr;
        } pipe_set_fragOffset_srcAddr;
        struct {
        } pipe_Reject;
        struct {
        } pipe_filter_tbl_NoAction;
    } u;
};
#if CONTROL_PLANE
static void init_tables() 
{
    uint32_t ebpf_zero = 0;
    {
        struct pipe_filter_tbl_value pipe_filter_tbl_NoAction_value = {
            .action = pipe_filter_tbl_NoAction,
            .u = {.pipe_filter_tbl_NoAction = {}},
        };
        INIT_UBPF_TABLE("pipe_filter_tbl_defaultAction", sizeof(ebpf_zero), sizeof(pipe_filter_tbl_NoAction_value));
        ubpf_map_update(&pipe_filter_tbl_defaultAction, &ebpf_zero, &pipe_filter_tbl_NoAction_value);
    }
}
#endif
#endif
